version: "3.9"

services:
  dashboard-chatbot:
    build:
      context: ./dashboard-chatbot
      dockerfile: Dockerfile
    container_name: dashboard-chatbot
    restart: always
    ports:
      - "${DASHBOARD_PORT}:3000"
    volumes:
      - ./dashboard-chatbot:/app
    networks:
      - chatbot-network
    depends_on:
      - api_mensagem

  db_chatbot:
    image: postgres:15
    container_name: db_chatbot
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - chatbot-network

  api_mensagem:
    build:
      context: ./api_mensagem
      dockerfile: Dockerfile
    container_name: api_mensagem
    ports:
      - "${API_PORT}:3001"
    volumes:
      - ./api_mensagem:/app
    environment:
      DB_HOST: db_chatbot
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    networks:
      - chatbot-network
    depends_on:
      - db_chatbot

  chatbot-erp:
    build:
      context: ./chatbot-erp
      dockerfile: Dockerfile
    container_name: chatbot-erp
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      CHROMIUM_PATH: ${CHROMIUM_PATH}
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      DB_HOST: db_chatbot
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${CHATBOT_PORT}:3000"
    volumes:
      - ./chatbot-erp:/usr/src/app
    networks:
      - chatbot-network
    tty: true
    shm_size: 1gb
    depends_on:
      - api_mensagem
      - db_chatbot

  telegram_bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: always
    ports:
      - "${TELEGRAM_PORT}:3002"
    volumes:
      - ./telegram-bot:/app
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db_chatbot
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    networks:
      - chatbot-network
    depends_on:
      - db_chatbot

networks:
  chatbot-network:
    driver: bridge