version: '3.8'
services:
  app:
    build: .
    container_name: api_mensagem_app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
